version: "3.9"

services:
  treino:
    build:
      context: .
    container_name: prophet-capture-and-train
    command: python capture_and_train.py
    volumes:
      - .:/app
    restart: "no"

  api:
    build:
      context: .
    container_name: prophet-api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - treino
    restart: unless-stopped
